const {
  SlashCommandBuilder,
  EmbedBuilder,
} = require("discord.js");
const MemberStats = require("../models/MemberStats");
const moment = require("moment");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("serverstats")
    .setDescription("💙 View futuristic join/leave server stats (SHADOW style)."),

  name: "serverstats",
  description: "💙 View futuristic join/leave server stats (prefix + slash)",

  async execute(context) {
    const { message, interaction, isPrefix } = context;
    const guild = isPrefix ? message.guild : interaction.guild;

    try {
      const today = moment().format("YYYY-MM-DD");
      const sevenDaysAgo = moment().subtract(6, "days");
      const thirtyDaysAgo = moment().subtract(29, "days");

      const stats = await MemberStats.find({
        guildId: guild.id,
        date: { $gte: thirtyDaysAgo.format("YYYY-MM-DD") },
      }).sort({ date: 1 });

      let todayData = stats.find((s) => s.date === today) || { joins: 0, leaves: 0 };
      let last7 = stats
        .filter((s) => moment(s.date).isAfter(sevenDaysAgo))
        .reduce(
          (acc, s) => {
            acc.joins += s.joins;
            acc.leaves += s.leaves;
            return acc;
          },
          { joins: 0, leaves: 0 }
        );

      let last30 = stats.reduce(
        (acc, s) => {
          acc.joins += s.joins;
          acc.leaves += s.leaves;
          return acc;
        },
        { joins: 0, leaves: 0 }
      );

      // Chart Data
      const labels = stats.map((s) => moment(s.date).format("DD MMM"));
      const joins = stats.map((s) => s.joins);
      const leaves = stats.map((s) => s.leaves);

      // Create a futuristic gradient chart using QuickChart.io
      const chartConfig = {
        type: "line",
        data: {
          labels,
          datasets: [
            {
              label: "Joins 💙",
              data: joins,
              borderColor: "rgba(0, 183, 255, 1)",
              backgroundColor: "rgba(0, 183, 255, 0.2)",
              borderWidth: 3,
              tension: 0.4,
              fill: true,
            },
            {
              label: "Leaves 💔",
              data: leaves,
              borderColor: "rgba(255, 99, 132, 1)",
              backgroundColor: "rgba(255, 99, 132, 0.15)",
              borderWidth: 3,
              tension: 0.4,
              fill: true,
            },
          ],
        },
        options: {
          plugins: {
            legend: {
              labels: {
                color: "#FFFFFF",
                font: { size: 14, family: "Poppins, sans-serif" },
              },
            },
          },
          scales: {
            x: {
              ticks: { color: "#b0c7ff" },
              grid: { color: "rgba(255,255,255,0.1)" },
            },
            y: {
              ticks: { color: "#b0c7ff" },
              grid: { color: "rgba(255,255,255,0.1)" },
            },
          },
        },
      };

      const chartUrl = `https://quickchart.io/chart?width=800&height=400&backgroundColor=transparent&c=${encodeURIComponent(
        JSON.stringify(chartConfig)
      )}`;

      // Futuristic Embed
      const embed = new EmbedBuilder()
        .setColor("#00B7FF")
        .setTitle(`<a:blue_heart:1414309560231002194> SHADOW Server Stats`)
        .setDescription(
          `📅 **Today:** +${todayData.joins - todayData.leaves} (**+${todayData.joins}**, **-${todayData.leaves}**)
🕒 **Last 7 Days:** +${last7.joins - last7.leaves} (**+${last7.joins}**, **-${last7.leaves}**)
🌐 **Last 30 Days:** +${last30.joins - last30.leaves} (**+${last30.joins}**, **-${last30.leaves}**)

> Showing smooth futuristic chart with 💙 SHADOW design.`
        )
        .setImage(chartUrl)
        .setThumbnail(guild.iconURL({ dynamic: true }))
        .setFooter({
          text: `Server: ${guild.name} • Generated by SHADOW`,
          iconURL: guild.iconURL({ dynamic: true }),
        });

      if (isPrefix) return message.reply({ embeds: [embed] });
      else return interaction.reply({ embeds: [embed] });
    } catch (err) {
      console.error("Error fetching server stats:", err);
      const errorMsg = "⚠️ Something went wrong fetching server stats.";
      if (isPrefix) message.reply(errorMsg).catch(() => {});
      else interaction.reply({ content: errorMsg, ephemeral: true }).catch(() => {});
    }
  },
};
